jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    password: jaspyt_password
    #iv-generator-classname: org.jasypt.iv.NoIvGenerator

# Get ClientId and ClientSecret from https://dashboard.groupdocs.cloud
groupdocs:
  client:
    id: ENC(bKKPWcm6JQZCSCyUDvY+fHwXUx2UgcN8oYXImsZdGuVUmJjk+ALf/SN7WcMNbLQU0z8Av8yrpXPPrXoG2oorv/SpNzn2txd/42ncLty2Imw=)
    secret: ENC(OmCxua9cTTe3F3s/UaNbVUru4YPzq9zA4ihoDRtdZWUt+whVd40AjT0jfTbSU2WyYvUmnYBy9R1UfCy2S+jGqimiH0w+Sr0Av+YoDiADPwA=)
  storage:
    name: ENC(pos10Cn6kutbLtYgzH1KJoOYZzbTRInek0BIf278hLRvQl/HmUwxmiowh0tqJvu/zDyR2qCbckr/D2n7AiOk0g==)

mytool:
  file:
    storage:
      code-mybook: /opt/mytool/files/code/mybook/
      groupdocs-conversion: /opt/mytool/files/groupdocs-conversion/