# Get ClientId and ClientSecret from https://dashboard.groupdocs.cloud
groupdocs:
  client:
    id: ENC(u5R9KkpmzRsnEC5RW1JFnDkctjYBPA5o/Fnr5d50QeqUgHuL57dI7dMcw7/RJ+i5)
    secret: ENC(jHgHqazyYllvPQinSRWZTZZPTn/O2+UCUhzYz+QlGh21i7UFvvEOo0um1noYiZfH)
  storage:
    name: ENC(DFMIh+Pf+7vwfAwVgYyNqDdQPZvraDr9MAzdGSmzqEs=)

mytool:
  file:
    storage:
      code-mybook: E:\Test\code\mybook\
      groupdocs-conversion: E:\Test\groupdocs-conversion\
      navicat: E:\Test\navicat\