server:
  port: 8080

spring:
  application:
    name: mytool
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

sentinel:
  qps:
    limit: 1

jasypt:
  encryptor:
    #algorithm: PBEWithHMACSHA512AndAES_256
    algorithm: PBEWithSHA1AndDESede
    password: jasypt
    #iv-generator-classname: org.jasypt.iv.NoIvGenerator
